### ISSUE TITLE
SSL issues

### ISSUE THREAD

**Issue by costronaut** [Sealjay/powerbi-adt#1]
Thank for the code, it does seems like something is missing. 
I tried it with multiple machine and they all return 
![image](https://user-images.githubusercontent.com/91554920/135146576-5443b30d-596b-48fa-b54d-90919a7bc772.png)

With and with az login. I'm not sure what i have been missing.

**Comment by Sealjay** [comment]
This looks related to an issue with Python installations, reviewing users with similar issues at Azure/azure-sdk-for-python#14498.

Based on research, this type of error could be a result of having outdated certificates in your Python installation. Given you're using PowerBI, I'm assuming you're on Windows - is this a recent Python install @costronaut ?

**Comment by Sealjay** [comment]
Closing for now - let me know if you're still having this issue @costronaut
